// Code generated by MockGen. DO NOT EDIT.
// Source: iFcmApi.go

// Package apiMock is a generated GoMock package.
package apiMock

import (
	context "context"
	model "pathfinder-family/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIFcmApi is a mock of IFcmApi interface.
type MockIFcmApi struct {
	ctrl     *gomock.Controller
	recorder *MockIFcmApiMockRecorder
}

// MockIFcmApiMockRecorder is the mock recorder for MockIFcmApi.
type MockIFcmApiMockRecorder struct {
	mock *MockIFcmApi
}

// NewMockIFcmApi creates a new mock instance.
func NewMockIFcmApi(ctrl *gomock.Controller) *MockIFcmApi {
	mock := &MockIFcmApi{ctrl: ctrl}
	mock.recorder = &MockIFcmApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFcmApi) EXPECT() *MockIFcmApiMockRecorder {
	return m.recorder
}

// CheckTokens mocks base method.
func (m *MockIFcmApi) CheckTokens(ctx context.Context, tokens []string) (*model.FcmApiResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTokens", ctx, tokens)
	ret0, _ := ret[0].(*model.FcmApiResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTokens indicates an expected call of CheckTokens.
func (mr *MockIFcmApiMockRecorder) CheckTokens(ctx, tokens interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTokens", reflect.TypeOf((*MockIFcmApi)(nil).CheckTokens), ctx, tokens)
}

// SendPush mocks base method.
func (m *MockIFcmApi) SendPush(ctx context.Context, request model.SendPushRequest, token string) (*model.FcmApiResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPush", ctx, request, token)
	ret0, _ := ret[0].(*model.FcmApiResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPush indicates an expected call of SendPush.
func (mr *MockIFcmApiMockRecorder) SendPush(ctx, request, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPush", reflect.TypeOf((*MockIFcmApi)(nil).SendPush), ctx, request, token)
}
